plfa/plfa.github.io

src/Properties.lagda

It looks like these lines were repeated twice in a row.
Unfortunately the diff below is not the optimal one.

remove repeated text

---

src/Naturals.lagda

In the example, the _second_ and not the _third_ equation is not used.
In fact, the third equation is used three times.

Wrong equation references in the text of Monus

---

src/plfa/Relations.lagda

"Rewriting by +-comm m p and +-comm n p converts m + p ≤ n + p into p + m ≤ p + n, which is proved by invoking +-monoʳ-≤ p m n m≤n."
The above sentence from the chapter "Relation: Monotonicity" as a conclusion, is not easy to grasp until someone knows how the notation "rewrite" works or has previously been familiar with the material from the chapter "Equality: Rewriting expanded".
In addition, the definition of monotonicity using the notation "with" could serve as an additional exercise, for example:
+-monoˡ-≤1 : ∀ (m n p : ℕ) → m ≤ n → m + p ≤ n + p
+-monoˡ-≤1 m n p mn with    m + p |  +-comm m p  | n + p  |  +-comm n p
...                                      | .(p + m)  | refl | .(p + n) | refl = +-monoʳ-≤ p m n mn

additional explanation on rewrite

---

src/plfa/Naturals.lagda

Hi, minor typo only (replace `suc n` by `suc m`) .

Fix typo (suc n → suc m)

---

src/plfa/Bisimulation.lagda
src/plfa/Connectives.lagda
src/plfa/DeBruijn.lagda
src/plfa/Decidable.lagda
src/plfa/Equality.lagda
src/plfa/Induction.lagda
src/plfa/Inference.lagda
src/plfa/Isomorphism.lagda
src/plfa/Lambda.lagda
src/plfa/Lists.lagda
src/plfa/More.lagda
src/plfa/Naturals.lagda
src/plfa/Negation.lagda
src/plfa/Quantifiers.lagda
src/plfa/Relations.lagda
src/plfa/SystemF.lagda
src/plfa/Untyped.lagda

Book builds and links work (including #sections). 
I assume that the link named More on line 729 of Untyped.lagda is intended to point to plfa.More, not plfa.Lambda, and have fixed this.

Use new local reference syntax

---

tspl/Assignment2.lagda

It seems like someone added the answer by accident. I noticed it when I pulled the latest and got a conflict.

Remove answer from recommended exercise

---

src/plfa/Lists.lagda

Fixed typo

---

src/plfa/Linearity.lagda

In this development, subst-split ended up just being a complicated way of getting hold of the linearity of matrix multiplication (that Δ(Γ₁ + Γ₂) = ΔΓ₁ + ΔΓ₂). I think it's still needed in my quantitative development because the underlying linear algebra is built intrinsically into resourced substitution, rather than being separated out. The extrinsic version here is far clearer.

Remove subst-split

---

src/plfa/Decidable.lagda
src/plfa/Equality.lagda
src/plfa/Induction.lagda
src/plfa/Lists.lagda
src/plfa/Naturals.lagda
src/plfa/Negation.lagda
src/plfa/Quantifiers.lagda

Some minor things I found while reading through the first part.
* Typos
- e.g. `suitabve` ~> `suitable`
* Phrasing
- e.g. `to universal of` ~> `to the universal of`
* Simpler imports
- e.g. `Data.Bool.Base` ~> `Data.Bool`
* Formatting
- e.g align clauses, unnecessary parentheses
* Forgotten unicode symbols
- e.g. `⊔` in `Equality.lagda`
* Alternative unicode commands
- e.g. `\ox` in addition to `\otimes`

Part I: Minor fixes

---

src/plfa/Naturals.lagda

Originally i wanted to point out that arbitrary-precision integers might be not the most precise term, because precision is often associated with reals, but apparently that's an established term. Then i noticed the integers are arbitary in one place ;)

Fix "arbitary" integers typo

---

src/plfa/Induction.lagda

This patch fixes a spelling error in the chapter on Induction. Commutativity was spelled as "Commutatitivity".

Fixes a spelling error in the chapter on Induction

---

extra/extra/InferenceOld.lagda
extra/extra/Lambda-new.lagda
extra/extra/PropertiesDec.lagda
extra/extra/SystemF.lagda
extra/stlc/StlcNew.lagda
extra/stlc/StlcOld.lagda
src/plfa/Bisimulation.lagda
src/plfa/DeBruijn.lagda
src/plfa/Induction.lagda
src/plfa/Inference.lagda
src/plfa/Lambda.lagda
src/plfa/More.lagda
src/plfa/Naturals.lagda
src/plfa/Properties.lagda
src/plfa/Quantitative.lagda
src/plfa/Untyped.lagda
tspl/Assignment4.lagda
tspl/Exam.lagda

This patch replaces all occurrences of 'judgement' with 'judgment' per @wadler's instruction.

Replaces all occurrences of 'judgement' with 'judgment'

---

src/plfa/Relations.lagda

This patch adds a full stop after two bullet points in the chapter on relations and an empty line after one of them so that there is a proper start of the paragraph following it.

Adds a full stop after two bullet points in the chapter on relations

---

src/plfa/Equality.lagda

This patch fixes a spelling of "anologue" in the chapter on equality.

Equality chapter: fixes spelling of a word

---

src/plfa/Equality.lagda

In the equality chapter, this fixes a recursive call to the intended addition commutativity. The first clause of `+-comm′` was changed to fix spacing in the light of the actual change.

Equality chapter: fixes a recursive call to the intended +-comm

---

src/plfa/Equality.lagda

This patch removes the "is" verb in a sentence where it doesn't belong. This is in the chapter on equality.

Equality chapter: removes a redundant verb

---

src/plfa/Isomorphism.lagda

In the isomorphism chapter, this inserts a line break so that a new paragraph starts after an enumeration. To me it makes sense to do this because otherwise the text talks about the third bullet point while under the fourth bullet point.

Isomorphism: inserts a line break for a new paragraph

---

extra/extra/PropertiesDec.lagda
src/plfa/Properties.lagda

This patch fixes spellings of a few words in the chapter on properties and in related material.

Properties: fixes spellings of a few words

---

extra/extra/DecidableExtra.lagda
src/plfa/Decidable.lagda

This fixes the spelling of "comparison" in the chapter on decidables.

Decidable: fixes the spelling of a word

---

src/plfa/Connectives.lagda

This patch fixes a typo and capitalises a word in the chapter on connectives.

Connectives: fixes a typo and capitalises a word

---

src/plfa/Isomorphism.lagda

This patch fixes wording in the chapter on isomorphism. It replaces "and" with "an", which is what I believe was intended in the sentence.

Isomorphism: replaces a conjunction with an article

---

src/plfa/Connectives.lagda

In the chapter on connectives, this patch changes "once member" to "one member" in a sentence:
"And, indeed, type `⊤` has exactly once member, `tt`."

Connectives: fixes a typo, once -> one

---

src/plfa/Connectives.lagda

Just like in the pull request #177, in the chapter on connectives this patch replaces "equation" with "propositional equality" to clarify where simplification happens.

Connectives: clarifies what simplification a pattern match enables

---

src/plfa/Connectives.lagda

In the chapter on connectives, this patch fixes an incorrect verb plural.

Connectives: fixes an incorrect verb plural

---

src/plfa/Connectives.lagda

Just like in the pull requests #177 and #179, in the chapter on connectives this patch replaces "equation" with "propositional equality" to better explain where simplification enables finishing a proof.

Connectives: fixes an explanation of simplification

---

src/plfa/Connectives.lagda

In the chapter on connectives, this patch replaces an occurrence of "as follows." with "as follows:". This is the only place in the whole `src` directory where a full stop was used after "as follows", unlike a colon that was used for 28 times.

Connectives: changes a punctuation before a code block

---

README.md

On the [Getting Started](https://plfa.github.io/GettingStarted/) page, there is a slight mismatch between badges on the top and corresponding links in the text:
- The Agda badge indicates version 2.5.4.2, while the text bellow links to the latest version. At the moment the latest Agda version is 2.5.4.2, but this can get out of sync.
- The standard library badge indicates version 0.17, while the text bellow links to the front page of the library repository, which might have changes that are not in version 0.17.
This patch pins down, i.e., fixes links to versions of Agda and the standard library so that they match versions indicated by the badges.

Getting Started: pins down software versions so badges match links

---

src/plfa/Lambda.lagda

I think ƛ should be used in the explanation so that it is not confused with the built-in λ in Agda.

Change λ to ƛ in Reduction

---

src/plfa/Negation.lagda

In the chapter on negation, this patch changes 'give' to 'given' as it should be in an explanation of a proof for the irrefutability of the excluded middle.

Negation: changes 'give' to 'given'

---

src/plfa/Quantifiers.lagda

This patch adds a missing adverb in the chapter on quantifiers.

Quantifiers: adds a missing adverb

---

src/plfa/Quantifiers.lagda

In the chapter on quantifiers this patch adds and removes spacing in expressions where this was needed for consistency with the rest of the text.

Quantifiers: fixes spacing in expressions

---

src/plfa/Quantifiers.lagda

In the chapter on quantifiers, this patch removes a back-tick that causes a formatting problem in the text explaining the proof of `even-∃`. With the back-tick in place, the text "which is immediate after substituting for" would end up highlighted like `which is immediate after substituting for`.
I'll just use this pull request to remind you of two other pending pull requests: PR #196 and PR #199. Let me know if I should make any changes there.

Quantifiers: removes a back-tick that causes a formatting problem

---

src/plfa/DeBruijn.lagda
src/plfa/More.lagda
src/plfa/Properties.lagda

The three chapters does not have unicode section, I added unicode sections for them.
As I did not collect unicode characters manually, I implemented some perl script to collect in the following criteria.
- If any unicode character that is appeared in the current chapter is picked up in unicode section, if the character is appeared at most once in any preceding chapters.
I sorted the character based on unicode code point.

Properties, DeBrujin, More: Missing unicode sections added

---

src/plfa/Properties.lagda

This is my mistake in my pr #211, which I found during unicode instruction generator implementation.

Properties: Unnecessary character removed.

---

src/plfa/Quantifiers.lagda

In the chapter on quantifiers, this patch adds a missing verb "is" in a sentence explaining a condition for a number to be odd.

Quantifiers: adds a missing verb

---

src/plfa/Quantifiers.lagda

In the chapter on quantifiers, this patch removes redundant spacing inside curly braces in an argument list to a function. This makes it consistent with the rest of the code.

Quantifiers: makes spacing consistent with the rest of the code

---

src/plfa/Decidable.lagda

In the chapter on decidables, this patch fixes a mistake where "is" was put in place of "if".

Decidable: replaces 'is' with 'if'

---

src/plfa/Decidable.lagda

In the chapter on decidables, this patch adds a colon before two snippets to make it consistent with the rest of the book.

Decidable: adds colons before code snippets

---

src/plfa/Decidable.lagda

In the chapter on decidables, this patch replaces "the" with "that" in a sentence that elaborates the proof for `_≤?′_`.

Decidable: replaces 'the' with 'that'

---

src/plfa/Decidable.lagda

In the chapter on decidables, this patch clarifies why is there no need for a case analysis. In particular, it is not that there is no need for a case analysis at all, but rather for one on the boolean `b` (there is a case analysis for the values of the `b ≡ true` type as otherwise there would be no case for `refl`).

Decidable: clarifies a lack of need for a case analysis

---

src/plfa/Lists.lagda

In the chapter on lists, this patch improves spacing in the definition of the `shunt` function such that patterns across equations are vertically aligned.

Lists: improves spacing in the definition of the shunt function

---

src/plfa/Lists.lagda

In the chapter on lists, this patch adds a colon before two snippets to make it consistent with the rest of the book.

Lists: adds colons before code snippets #2

---

src/plfa/Lists.lagda

In the chapter on lists, this patch adds an intermediate step in a proof of `++-assoc`. Without this step it was not obvious to me why the equation preceding it is equal to the one following it. The introduction of this intermediate step should make it easier to see why.

Lists: adds an intermediate step in a proof for ++-assoc

---

src/plfa/Lists.lagda

In the chapter on lists, this patch adds a colon before two snippets to make it consistent with the rest of the book.

Lists: adds colons before code snippets

---

src/plfa/Lists.lagda

In the chapter on lists, this patch fixes the usage of the cons operator by replacing a two-colon symbol `_::_` (which is not actually used in the definition of lists) with a single-colon symbol `_∷_`.

Lists: fixes the symbol for the cons operator

---

src/plfa/Decidable.lagda

In the chapter on decidables, this patch removes unused and unrelated imports. For example, the chapter does not talk about lists at all so there is no need to import list constructors and list functions. The chapter type-checks just fine after removing these imports.

Decidable: removes unused and unrelated imports

---

src/plfa/Lists.lagda

In the chapter on lists, this patch replaces an "and" with an "or" in the definition of a higher-order function. Either criterion is enough to meet the definition, hence "or".

Lists: updates the definition of a higher-order function

---

src/plfa/Quantifiers.lagda

In the chapter on quantifiers, this patch removes unused imports. The chapter file type-checks with these changes.

Quantifiers: removes unused imports

---

src/plfa/Isomorphism.lagda

In the chapter on isomorphism, this patch removes unused imports. The chapter file type-checks with this update.

Isomorphism: removes unused imports

---

src/plfa/Connectives.lagda

In the chapter on connectives, this patch removes unused imports. The chapter file type-checks with this update.

Connectives: removes unused imports

---

src/plfa/Negation.lagda

In the chapter on negation, this patch removes unused imports. The chapter file still type-checks after this update.

Negation: removes unused imports

---

src/plfa/Lists.lagda

In the chapter on lists, this patch removes a your-code-goes-here code snippet as there is nothing to implement there; an implementation for `_∘′_` is provided just above it.

Lists: removes a your-code-goes-here snippet

---

index.md

This simple patch removes an extra space from the table of contents.

Removes an extra space from the table of contents

---

src/plfa/Relations.lagda

Since Monotonicity is defined as `∀ {m n p q : ℕ} → m ≤ n → p ≤ q → m + p ≤ n + q`, and the final proof uses the transitivity of `+-monoˡ-≤` and `+-monoʳ-≤`, it seems better to have `+-monoʳ-≤` parameters as `∀ (n p q : ℕ)` so the transition from `m + p ≤ n + p` to `n + p ≤ n + q` becomes consistent with its definition. This is already the case in the definition of `+-monoˡ-≤`.

Change in the first argument of +-monoʳ-≤

---

src/plfa/Equality.lagda

I think the first one is 'that', and in the exercise, it meant to be `+-monoˡ-≤` and `+-monoʳ-≤`.
Also, the `≡-Reasoning` defined earlier uses capital R.

Fixed some typos in Equality chapter

---

src/plfa/Relations.lagda

Typo: that ~> than

---

src/plfa/Induction.lagda

this call to assoc references the binder `m` , however `m` is not involved in this step of the proof

fix typo in call to assoc

---

src/plfa/Lists.lagda

In the chapter on lists, this patch fixes the plural of a noun as well as names of analogues in an exercise `any?`.

Lists: fixes the plural and names of analogues in exercise text

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch adds a missing preposition in the prose.

Lambda: Adds a missing preposition in the prose

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch fixes a quiz question by replacing `two` with `twoᶜ`.
Closes #252.

Fixes a quiz question involving twoᶜ

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch adds a missing word "step" in the prose on reduction closure.

Lambda: adds a missing word in the prose on reduction closure

---

src/plfa/Decidable.lagda

In the chapter on decidables, this patch makes usage of a more specific relation symbol to make it clear that it is the `_≤ᵇ_` function that is talked about instead of the relation `_≤_`.

Decidable: uses a more specific relation symbol

---

src/plfa/Lists.lagda

The order of the inductive hypothesis in the description of `++-assoc` doesn't match its order in the proof.

Lists: Change in the order of hypothesis in ++-assoc's description

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this simple patch fixes the plural of a word.

Lambda calculus: fixes a plural in the prose

---

src/plfa/Lambda.lagda

Variables "s" and "z" weren't rendering in code style, and in the exercise, the code parts were both indented and surrounded in back-quotes.

Fixed some markdown parts

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch fixes the symbol used for types in a typing context (a plain colon replaced with `\:` in the Agda input method).

Lambda: fixes typing symbols in a context

---

src/plfa/Lambda.lagda

I didn't see Γ being listed at the end of previous chapters. Also, fixed a link.

Added a missing Unicode in Chapter Lambda

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch removes  a double preposition in a sentence about `impossible`.

Lambda: removes a double preposition in a sentence about impossible

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch fixes a typo in "numberal" in a sentence on Church numerals.

Lambda: fixes a typo in a sentence on Church numerals

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this patch fixes a verb tense by replacing "type" with "typing".

Lambda: fixes a verb tense

---

src/plfa/DeBruijn.lagda

Replaced `Ax` with  `` ⊢` `` in `⊢plus`, and fixed the markdown style of some variable names.

DeBruijn: Replaced Ax with  ⊢` in the second example

---

extra/extra/Lambda-new.lagda
index.md
src/plfa/DeBruijn.lagda
src/plfa/Denotational.lagda
src/plfa/Lambda.lagda

There was a mixture of using 'De Bruijn' and 'de Bruijn' in Chapter DeBruijn and some other parts of the book, I replaced all of them with 'de Bruijn' except the ones at the beginning of the sentences.

Replaced occurrences of 'De Bruijn' with 'de Bruijn'

---

src/plfa/Lambda.lagda

In the chapter on lambda calculus, this simple patch adds a full stop at the end of a sentence.

Lambda: adds a full stop at the end of a sentence

---

src/plfa/DeBruijn.lagda

Changed `two` to `twoᶜ` and `⇒` to `→`, and cleaned up some spacing.

DeBruijn: Fixed the introduction example

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch adds full stops to two places.

Lambda: adds punctuation to a couple of places

---

src/plfa/DeBruijn.lagda

I think the first 'for example' sentence was supposed to be removed after the addition of the next one.

DeBruijn: Removed a redundant sentence

---

extra/qtt/Quantitative.lagda

This patch fixes a spelling error in a chapter on quantitative type theory.

Quantitative: fixes a spelling error

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch expands the BNF abbreviation as that is the first time ever in the book that it is used.

Lambda: expands the BNF abbreviation

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch splits a sentence about the `sucᶜ` function into two sentences. The first part of the original sentence doesn't have much to do with the second part. By splitting it into two sentences it makes it easier to understand how a Church numeral is converted to the corresponding natural.

Lambda: splits a sentence into two sentences

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch adds full stops at the end of sentences in several examples.

Lambda: adds full stops at the end of several examples

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch adds full stops to two sentences in a substitution example.

Lambda: adds full stops at the end of sentences in an example

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch makes spacing consistent around `≡` in substitution examples.

Lambda: makes spacing consistent in substitution examples

---

src/plfa/Properties.lagda

In the chapter on properties, this patch fixes an analysis of the `canonical` function. In particular, the analysis used to say that cases for zero and successor are thrown out, which is not true and it contradicts the paragraph preceding it. Instead, the patch fixes that by saying that case expression is thrown out, which wasn't mentioned.

Properties: fixes an explanation of the canonical function

---

src/plfa/Lambda.lagda

In the introductory chapter on lambda calculus, this patch aligns a dashed line in the rule for the ``⊢` `` typing judgment such that a premise and the conclusion start in the same column.

Lambda: aligns an inference rule line

---

src/plfa/Properties.lagda

In the chapter on properties for lambda calculus, this patch fixes the plural of a noun.

Properties: fixes the plural of a noun

---

src/plfa/Properties.lagda

In the chapter on lambda calculus properties, this patch adds a missing pronoun.

Properties: adds a missing pronoun

---

src/plfa/Properties.lagda

In the chapter on properties, this simple patch changes the indentation of the `rename` function's signature. This is to make it consistent with indentation in other function signatures elsewhere in the book.

Properties: changes the indentation of the rename function's signature

---

src/plfa/Properties.lagda

In the chapter on properties, this simple patch adds a full stop at the end of a sentence.

Properties: adds a full stop at the end of a sentence

---

_sass/agda.scss

The font name "Dejavu" and it's path should be "DejaVu".
The previous name and it's path "Dejavu" will cause jekyll shows:
`"ERROR '/assets/fonts/DejavuSansMono.woff2' not found"`,
which actually in `/assets/fonts/DejaVuSansMono.woff2`.

Fix DejaVu font name and path

---

src/plfa/DeBruijn.lagda.md

Changed `` `ℕ → `ℕ `` to `` `ℕ ⇒ `ℕ ``, removed an unnecessary space, and combined implicit arguments on a couple of constructors.

DeBruijn: Fixed some styling issues

---

src/plfa/Properties.lagda.md

In the chapter on properties, this simple patch fixes a typing judgment in prose by replacing an identifier with a term.

Properties: fixes a typing judgment by replacing an identifier with a term

---

src/plfa/Lambda.lagda.md

In the introductory chapter on lambda calculus, this patch fixes the usage of "well typed" per issue #318.

Lambda: fixes the 'well typed' usage per issue #318

---

src/plfa/Inference.lagda.md

In the chapter on inference, this simple patch fixes the usage of "ill typed" analogous to issue #318.

Inference: fixes the usage of 'ill typed' per issue #318

---

src/plfa/More.lagda.md

In the chapter on additional constructs of STLC, this one-line patch fixes the usage of "well typed" per issue #318.

More: Fixes the usage of 'well typed' per issue #318

---

src/plfa/DeBruijn.lagda.md

In the chapter on DeBruijn indices, this simple patch fixes the usage of "well typed" vs. "well-typed" per issue #318.

DeBruijn: fixes the usage of 'well typed' per issue #318

---

highlight.sh

In the last line of https://plfa.github.io/Lambda/#formal-vs-informal
we get a spurious link to the standard library because the script
happily matches "Agda."
Note that I couldn't test this as `make` fails with weird warnings
on my laptop.

[ fix ] bug in the last line of Formal vs. Informal

---

src/plfa/Naturals.lagda.md

In the chapter on naturals, this patch fixes the usage of "well founded" analogous to the usage of "well-typed" per issue #318.

Naturals: fixes the usage of 'well founded' analogous to issue #318

---

src/plfa/Induction.lagda.md

In the same manner as https://github.com/plfa/plfa.github.io/pull/368, in the chapter on induction this patch fixes the usage of "well-founded" analogous to the usage of "well-typed" per issue #318.

Fixes the usage of 'well-founded' analogous to the issue #318

---

src/plfa/Properties.lagda.md

In the chapter on properties, this patch adds a sentence about canonical forms. I'm not completely sure if it makes a good statement, but with this I at least wanted to start a discussion on what are canonical forms; the prose no where says that at the moment.

Properties: adds a sentence on canonical forms

---

src/plfa/DeBruijn.lagda.md
src/plfa/More.lagda.md

- In `caseL L [nil⇒ M | x ∷ y ⇒ N ]`, `nil` is actually `[]` in the following usages of `caseL`.
- In `mapL`, the argument of `μ` matches what comes in the body of the function.
- Some dashed-line aligning.

Fixed some styling issues

---

src/plfa/DeBruijn.lagda.md
src/plfa/More.lagda.md

Combined implicit arguments of `begin_` function, and removed unnecessary implicit argument assigning.
For `V-con`, I think the implicit context `Γ` should go after `con` to be consistent with what is happening to `V-zero`, and the explanation of the previous chapter for it:
> Here zero requires an implicit parameter to aid inference, much in the same way that [] did in Lists.
It is also already the case in `δ-*`.

Changed some implicit arguments

---

src/plfa/Bisimulation.lagda.md

I think substitution meant to be more complex than _renaming_.
Also, there is a sentence regarding extending the environment that says
> in this case, only for the body of an abstraction.
But extending is also needed for `~let`, so I don't know if this sentence needs to change or "an abstraction" means both `~ƛ` and `~let` since `~let` is translated to an abstraction.

Bisimulation: Fixed a sentence

---

src/plfa/part1/Relations.lagda.md

Since `_*_` is needed for `*-mono-≤`, readers shouldn't have to import `_*_` on their own.

part1/Relations: add product import

---

courses/puc/2019/tspl2019.agda-lib

Adding this missing file fixes the import issue:
```
The name of the top level module does not match the file name. The
module Assignment1 should be defined in one of the following files:
...
```

Add missing library file

---

src/plfa/part1/Relations.lagda.md

Removed the _*_ import since based on the discussions in #272, imports for exercises are not needed.

Relations: Removed the unnecessary _*_ import

---

Makefile

`bash` is not specified to reside under `/bin/bash` on all OSs. E.g. on NixOS it does not.

Don't hardcode executable paths

---

src/plfa/part1/Lists.lagda.md

Minor fix. Title plus the context of the change should make intent clear.

Fix: make capitalization consistent.

---

src/plfa/part2/DeBruijn.lagda.md
src/plfa/part2/Inference.lagda.md
src/plfa/part2/More.lagda.md

* Re-export test examples from Chapter DeBruijn in Chapter More.
* In Chapter Inference, as well as Assignment 4, import the
instrinsically-typed λ-calculus as follows:
`import plfa.part2.More as DB`

Consistent import of DB

---

src/plfa/part1/Lists.lagda.md

The `merge` relation can be illustrated as follow:
merge xs ys zs ≡ xs + ys = zs
This shows a key point: every element of `xs` is contained in `zs`.
The original definition of `split` makes no sense under this revelation.
split : ∀ {A : Set} {P : A → Set} (P? : Decidable P) (xs : List A)
→ ∃[ ys ] ∃[ zs ] ( merge xs ys zs × All P ys × All (¬_ ∘ P) zs )
`zs` will contain all elements of `xs` (the input!) and we also have that `All (¬_ ∘ P) zs`. This function signature cannot be inhabited, as it would imply that for any `P : A → Set` and any `x : A` we have `¬(P x)`.
This pull request fixes the described issue and modifies the explanation of the `split` exercise a little.

Fix: order of parameter in `split` function.

---

assets/main.scss

See https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside
This ensures that, when printing a chapter of the book, code will attempt to stay on a single page.

Avoid page breaks inside code when printing

---

src/plfa/part2/Lambda.lagda.md

In the chapter on lambda calculus, this simple patch changes how the `suc` constructor is given in the text. A consistent way in the introduction of the chapter would be: `suc` is given an argument, `zero` takes no arguments and `case` takes 4 arguments.

Lambda: give the suc constructor is the text with an argument

---

src/plfa/part2/Lambda.lagda.md

In the chapter on lambda calculus, this simple patch fixes indentation such that the Markdown under consideration is rendered in a box.

Lambda: fix indentation for correct rendering

---

src/plfa/part2/Lambda.lagda.md

In the chapter on lambda calculus, this patch fixes a term in an example showing that typing relation is not injective by replacing an identifier with a variable.

Lambda: fix the term in an example showing typing relation is not injective

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties in the proof of the `swap` lemma, this patch changes the name of a proof of z ≢ x in a case analysis. Namely, given that the sub-lemma `ρ` is about showing that `z` has type `C` in the given context, in the construction of `ρ`:
```agda
ρ : ∀ {z C}
→ Γ , y ⦂ B , x ⦂ A ∋ z ⦂ C
--------------------------
→ Γ , x ⦂ A , y ⦂ B ∋ z ⦂ C
ρ Z                   =  S x≢y Z
ρ (S y≢x Z)           =  Z
ρ (S z≢x (S z≢y ∋z))  =  S z≢y (S z≢x ∋z)
```
the second case should instead read:
```agda
ρ (S z≢x Z)           =  Z
```
Of course, the proof still holds.

Properties: rename a proof for z ≢ x

---

src/plfa/part2/Properties.lagda.md

In the chapter on Properties, this patch fixes the inductive hypothesis for lambda abstraction in the description of the proof of `subst`.
I might be wrong, but my understanding of the `subst` lemma is that its conclusion has one element fewer in the context than its antecedent.

Properties: fix the inductive hypothesis for lambda abstraction

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties, this patch fixes the usage of 'well typed' according to issue #318.

Properties: fix 'well-typed' according to issue #318

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties, this patch fixes a double plural mistake in "reductions sequences".

Properties: fix a double plural mistake

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties, this patch visually aligns pattern-matches for `M —→ N` in the proof of `preserve`. Of course, the proof type-checks without the parentheses, but having them is more visually appealing by bringing it in line with the rest of the pattern-matches, including with that of `(β-μ)` where parentheses are not mandatory either.

Properties: visual alignment of pattern matches for M —→ N

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties, this patch fixes an informal rule in the text for `β-ƛ` by using a reduction relation instead of the typing judgment.

Properties: fix an informal rule in the text for β-ƛ

---

src/plfa/part3/Denotational.lagda.md

In the chapter on denotational semantics of untyped lambda calculus, this simple patch removes a double occurrence of "to".

Denotational semantics: remove a double 'to'

---

src/plfa/part1/Naturals.lagda.md

Hello! Firstly, thank you for writing this book — I am excited to work through it!
Secondly, the reason for this pull request! Coming from Haskell, I am used to placing my LANGUAGE pragmas at the top of my file, and ended up upsetting Agda when trying to do the same when working through the Naturals chapter. It wasn't clear to me when working through the chapter that the pragma statements actually look for previously defined bindings within the module (and additionally that the built-ins can be bound to any name — neat!). It became clear once I read [the docs](https://agda.readthedocs.io/en/v2.5.4.1/language/built-ins.html#natural-numbers) that this is indeed the case. 
Hoping this minor addition to the section on using the built-in pragmas can help future readers.

Add note about Agda pragma placement

---

src/plfa/part1/Naturals.lagda.md

Correct wrong book title. The book is called Begriffsschrift.

Correct wrong book title

---

src/plfa/part1/Induction.lagda.md

Remove a strange line break in the middle of the formula. I guess the mark-down respects that line break because it's part of the formula.

Remove strange line break

---

src/plfa/part2/Substitution.lagda.md

`M` on the right hand side of `≡` should be `M′`.

Fix cong-rename

---

src/plfa/part2/Properties.lagda.md

The first formalization of the lambda using strings for variables has at least one pretty subtle point, which I probably overlooked in the text. For example, it matters a lot whether you write  y ≟ x or  x ≟ y. In one case, the proofs go through nicely, but in the other case Agda dumps a screenful of messages from the low level implementation of string comparison on you.

proposed text addition: pragmatic note on matching against decidable equality

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties, this tiny patch fixes the rendering of a highlighted expression `plus ·
two · two` by removing a line break in the expression. The current broken rendering can be seen in the attached screenshot.

Properties: fix the rendering of a highlighted expression

---

src/plfa/part2/Lambda.lagda.md

In the chapter Lambda, this simple patch highlights "n" and "m" in a sentence the same way they are highlighted in the sentence preceding it.

Lambda: fix highlighting of bindings in the text

---

Makefile
epub/rewrite-links.lua
src/plfa/part2/More.lagda.md

This brings us down to 10 `epubcheck` warnings. This is done with a lua filter that rewrites links with regular expressions.
References #480.

EPUB: Fix broken links

---

src/plfa/dedication.md

With this PR and #484, epubcheck gives no more warnings.
HTML does not permit nested `<p>` elements, which epubcheck complains
about. This change fixes those remaining warnings.
This change also causes the Dedication on the website to be centered
when viewed in Safari, which it was not before. Other than that, the Dedication
looks the same in the EPUB and website version.
Closes #480.

Fix remaining epubcheck warnings

---

src/plfa/part1/Relations.lagda.md

While working through the `Relations` chapter I noticed that the type of `odd`'s `suc` constructor didn't line up with the types of the two `even` constructors, so I thought I'd submit a pedantic single-character-diff pull-request. 😅

Align type definitions in even and odd example

---

src/plfa/part2/Confluence.lagda.md

Regarding #473, this is my first try in reformulating the diamond property (triangle property, actually) using Takahashi's approach. I am not a very good storyteller, so the informal development might need to be polished further. Please feel free to improve my wording.
Thanks to Andrea @iwilare for the naming and the triangle diagram, I implemented them altogether. 
For the record, here are the details of my changes. 
* There are more high-level descriptions but less Agda code obviously. The main difference in terms of proofs between these two properties is that a single induction on `M ⇛ N` suffices to prove the triangle property instead of a double induction to prove the diamond property. The latter involves actually a number of cases eliminated implicitly by unification in Agda.
* The …

[ re #473 ] Takahashi's complete development

---

src/plfa/part2/Properties.lagda.md

In the chapter on properties, this simple patch introduces an implicit argument `M` for clarity in the type of M-named variables in the proof of `eval`. The patch makes the proof more pedagogical and easier to write with Agda's interactive type-driven development.
Without the patch, the types of variables are confusing, e.g., the variable `M—↠N` has type `N —↠ N₁`. For the following code with a hole:
```agda
eval : ∀ {L A}
→ Gas
→ ∅ ⊢ L ⦂ A
---------
→ Steps L
eval {L} (gas zero)    ⊢L                              =  steps (L ∎) out-of-gas
eval {L} (gas (suc m)) ⊢L with progress ⊢L
... | done VL                                          =  steps (L ∎) (done VL)
... | step L—→M with eval (gas m) (preserve ⊢L L—→M)
...    | steps M—↠N fin                                =  {!!}
```
the goal …

Properties: introduce an implicit argument M for clarity in the type of M-named variables

---

src/plfa/part1/Decidable.lagda.md

This was exactly the same issue as #498. Kramdown treats newlines in code spans as literal newlines. Moving the newline out of the code span means the paragraph renders as expected.

Fix newline rendering in Decidable chapter

---

src/plfa/part1/Quantifiers.lagda.md

This PR fixes a small layout issue in the Quantifiers chapter. There was a newline in the middle of a code span, which caused the code to render like this: 
By moving the newline out of the code span, it now renders like this, which I presume was the intention:
(I think this is a quirk of Kramdown specifically, as Github Markdown renders this sort of situation `like
this`.)

Fix newline rendering in Quantifiers chapter
