src/Naturals.lagda

First, I just wanted to thank you for writing this book. :) I'm Agda-curious and bookmarked your book as soon as I saw it. I'm interested in switching from Coq to Agda for my proofs (maybe), and I'm looking forward to learning how it fares without tactics.
This PR just fixes a minor English usage problem in the exposition on natural numbers.

Replace 'less' with 'fewer'

---

src/Quantifiers.lagda

This looks like a small typo in an equation

Fix typo in an equation in quantifiers

---

src/Quantifiers.lagda

Fixes order of terms in formulas within comments to match the theorems

Fix typos in equations in Quantifiers.lagda

---

src/plfa/Naturals.lagda

two typo errors I made while editing the **Naturals. lagda** file

Autocorrection to commit #32

---

src/plfa/Isomorphism.lagda

remove the parentheses to be consistent with the other chapters

parentheses removing

---

src/plfa/Inference.lagda

I think there's a minor type in the Inference chapter.

Typo: M- -> M^-

---

tspl/Assignment1.lagda

Exercise #odd-plus-odd in Assignment 1 requires some imports from plfa.Relations

Import even, odd and their constructors

---

src/plfa/Lambda.lagda

Fix code highlighting, typo

---

src/plfa/Induction.lagda

This patch fixes a grammar issue in the chapter on induction.

Fixes a grammar issue in the chapter on induction

---

src/plfa/Lists.lagda

This is my last adjustment at the moment.
Before I proceed with the revision of Part 2, I have to read it carefully several times.

Last Update Lists.lagda

---

src/plfa/Lambda.lagda

Code is prettier when it's quoted

Improved markup

---

src/plfa/DeBruijn.lagda

Not sure if it was meant as "to do to cover" or "to cover", but i believe the latter should be enough

Fix typo/style in DeBrujin

---

src/plfa/Isomorphism.lagda

I guess that is what's intended.

Small fix.

---

extra/extra/Lists-backup.lagda
src/plfa/Lists.lagda

This fixes spellings of several words in the chapter on lists.

Lists: fixes spellings of several words

---

src/plfa/Decidable.lagda

Fix spelling mistake

---

extra/extra/Logic.lagda
src/plfa/Connectives.lagda

This patch changes "cartesian" to "Cartesian".

Capitalises 'cartesian'

---

src/plfa/Bisimulation.lagda
src/plfa/Connectives.lagda
src/plfa/DeBruijn.lagda
src/plfa/Decidable.lagda
src/plfa/Equality.lagda
src/plfa/Induction.lagda
src/plfa/Inference.lagda
src/plfa/Isomorphism.lagda
src/plfa/Lambda.lagda
src/plfa/Lists.lagda
src/plfa/More.lagda
src/plfa/Naturals.lagda
src/plfa/Negation.lagda
src/plfa/Properties.lagda
src/plfa/Quantifiers.lagda
src/plfa/Relations.lagda
src/plfa/Untyped.lagda

Added code blocks to every exercise in PLFA

---

src/plfa/Lambda.lagda
src/plfa/Properties.lagda

Input method for EMPTY SET added.

EMPTY SET added for input.

---

src/plfa/Properties.lagda

Though it's not a real issue, appearance will get consistent with this change.

Minor alignment change.

---

src/plfa/DeBruijn.lagda

Duplicated word removed.

---

src/plfa/Quantifiers.lagda

In the chapter on quantifiers, this patch puts the correct data constructor for an existential mentioned in the text.

Quantifiers: puts the correct data constructor for an existential

---

src/plfa/More.lagda

More: Fix typos.

---

src/plfa/Relations.lagda

In the chapter on relations, this patch removes unused imports. The chapter file type-checks with this update.

Relations: removes unused imports

---

src/plfa/Relations.lagda

relating -> relation

---

src/plfa/Lambda.lagda

My apologies, I forgot to update the quiz question too in PR #254. This takes care of it.

Follow up to PR #254: replaces two with twoᶜ in the quiz question

---

src/plfa/Lambda.lagda

Regarding #274, adding not-equal.

Lambda: Added ≠ to the list

---

src/plfa/Connectives.lagda

The -> Then

---

tspl/Assignment3.lagda

In the TSPL assignment 3, this patch fixes two spelling errors.

TSPL Assignment 3: fixes two spelling errors

---

tspl/PUC-Assignment2.lagda

In TSPL, this patch fixes a few spelling errors in PUC Assignment 2.

TSPL: a few spelling error fixes in PUC Assignment 2

---

src/plfa/Decidable.lagda.md

I think #340 was closed incorrectly without fix.
So i submit this PR and then merge it back to https://github.com/Agda-zh/PLFA-zh/pull/62

Fix typo in Decidable #340

---

_includes/script.html
assets/main.scss

Reverts plfa/plfa.github.io#348

Revert "Fix #347"

---

.travis.yml

Idea from https://blog.esciencecenter.nl/travis-caching-and-incremental-builds-6518b89ee889
and tool from https://github.com/MestreLion/git-tools/blob/master/git-restore-mtime
Evidence: https://travis-ci.org/Agda-zh/PLFA-zh/jobs/560033018

Use a trick to speed up travis builds

---

src/plfa/Lambda.lagda.md

add space in the syntax of terms in BNF

---

src/plfa/More.lagda.md

Added a missing closing bracket, and fixed a couple of `⇒` arrows.

More: Added a missing bracket, and fixed arrows

---

src/plfa/More.lagda.md

It seems the type is being called `Nat` in the rest of the chapter.

More: Fixed a type name

---

src/plfa/DeBruijn.lagda.md

I hope the request is useful this time.  I did not parse the first sentence.

remove 'map', variable -> variables

---

src/plfa/Bisimulation.lagda.md

Added a space in `[ x := V ]`.

Bisimulation: Added a space

---

src/plfa/part1/Relations.lagda.md

"form `m ≤ n`" -> "from `m ≤ n`"

part1/Relations: Fix Typo

---

beta.md
index.md
src/plfa/part3/Soundness.lagda.md

Changed occurrences of "inherent" on index and Part 3 to "intrinsic"; regarding #389.

Changed missed inherent occurrences to intrinsic

---

src/plfa/preface.md

Changed the labeling description of practice exercises in Preface to go with changes from #383.

Changed the description of practice exercises

---

README.md

Fix "Github" typo

---

src/plfa/part1/Naturals.lagda.md

Indent by two spaces instead of three.

Consistent formatting

---

src/plfa/part1/Lists.lagda.md

Implemented things discussed in #412

[ implement ] issue #412

---

src/plfa/part2/Lambda.lagda.md

fixed a malformatted code block in the chapter "Lambda"

[ fix ] inline code block

---

src/plfa/part1/Lists.lagda.md

Minor fix. Title says everything.

Fix: missing close backquote on inline code.

---

src/plfa/part2/Inference.lagda.md

I think this is a copy-and-paste error from the previous paragraph.

Inference: a variable -> an abstraction

---

src/plfa/part1/Relations.lagda.md

Just a tiny change, sorry if this is nitpicking !

consistent variable name typo

---

extra/extra/Logic.lagda
src/plfa/part1/Connectives.lagda.md

Make sum type right-associative

---

README.md
src/plfa/part1/Naturals.lagda.md

Here are pull requestl regarding #448.

Mentioning emacs unicode command #448

---

_sass/agda.scss

Avoid line breaks in the middle of code

---

_includes/script.html

Use anchorjs for generating anchors

---

.gitignore
.travis.yml
Makefile
README.md
epub/index.md
epub/rewrite-html-ul.lua
epub/run-liquid.lua
src/plfa/acknowledgements.md

See the commit message for more information.
References #480.

EPUB output: Populate acknowledgements.md with contributors
